Fourth challenge
kristiansantos/onboarding_environment pull request #5
Opened 2022-04-12 13:23 UTC by kristiansantos

Request code review.

2022-04-13 17:57 UTC, leoribeiro36 commented on phoenix/app/products_manager/test/products_manager/contexts/manager_test.exs
> +  describe "Update product" do
também tem o caso do produto não ser encontrado

2022-04-13 17:57 UTC, leoribeiro36 commented on phoenix/app/products_manager/test/products_manager/contexts/manager_test.exs
> +  describe "Delete product" do
também tem que testar quando o produto não é encontrado

2022-04-13 17:57 UTC, leoribeiro36 commented on phoenix/app/products_manager/test/products_manager/contexts/manager_test.exs
> +  describe "List products" do
A forma que você está usando o describe não está errada, foi o padrão que você optou, mas se quiser usar o padrão que utilizamos aqui é assim:
```
describe "get_orders/3" do
    test "with success"
    ...
    test "with success when not specifying a starting date"
```
pois no caso a descrição indica o endpoint ou funcionalidade que está sendo testado e o teste contém só uma breve descrição do esperado

2022-04-13 17:57 UTC, leoribeiro36 commented on phoenix/app/products_manager/test/products_manager/services/elasticsearch_test.exs
> +defmodule ProductsManager.ElasticSearchTest do
conforme conversado pode apagar esse arquivo e adicionar às funcionalidades que utilizam o els

2022-04-13 17:57 UTC, leoribeiro36 commented on phoenix/app/products_manager/test/products_manager/services/redis_test.exs
> +defmodule ProductsManager.RedisTest do
esse arquivo também pode ser removido e testado junto a outras funcionalidades

2022-04-13 18:28 UTC, NoahCamargo requested changes

2022-04-13 18:28 UTC, NoahCamargo commented on phoenix/app/products_manager/lib/products_manager/services/elasticsearch.ex
>    def get_all(array_conditions, source) do
Por conveniência, é costumeiro deixar os parâmetros na mesma order em função de mesma assinatura. Exemplo:

```
def get_all(source) do
def get_all(source, array_conditions) do
```
chamada:

```
get_all(@source)
get_all(@source, params_to_list)
```

Dessa forma é mais difícil de gerar confusão na hora de utilizar a função

2022-04-13 18:28 UTC, NoahCamargo commented on phoenix/app/products_manager/test/products_manager/contexts/manager_test.exs
> +    test "list_products/0 returns all products", %{product: product} do
Esse é o caso vindo do elastic ou do banco? Como cobertura, é bom ter os dois

2022-04-13 18:28 UTC, NoahCamargo commented on phoenix/app/products_manager/test/products_manager/contexts/manager_test.exs
> +    test "list_products/1 returns search products", %{product: product} do
Esse é o caso vindo do elastic ou do banco? Como cobertura, é bom ter os dois

2022-04-13 18:28 UTC, NoahCamargo commented on phoenix/app/products_manager/test/products_manager/contexts/manager_test.exs
> +    test "get_product/1 returns the product with given id", %{product: product} do
Esse teste é quando esta no Redis ou no banco? É bom validar ambos e checar o caso em que não estava no redis e verificar se depois do get foi para o redis e o elastic

2022-04-13 18:28 UTC, NoahCamargo commented on phoenix/app/products_manager/test/products_manager/contexts/manager_test.exs
> +  describe "Create products" do
Valide se foi de acordo para o redis e elastic

2022-04-13 18:28 UTC, NoahCamargo commented on phoenix/app/products_manager/test/products_manager/contexts/manager_test.exs
> +    test "create_product/1 with invalid data returns error changeset" do
Verifique se os erros são o que voce esperava

2022-04-13 18:28 UTC, NoahCamargo commented on phoenix/app/products_manager/test/products_manager/contexts/manager_test.exs
> +  describe "Update product" do
Valide se foi de acordo para o redis e elastic

2022-04-13 18:28 UTC, NoahCamargo commented on phoenix/app/products_manager/test/products_manager/contexts/manager_test.exs
> +    test "update_product/2 with invalid data returns error changeset", %{product: product} do
Verifique se os erros são o que voce esperava

2022-04-13 18:28 UTC, NoahCamargo commented on phoenix/app/products_manager/test/products_manager/contexts/manager_test.exs
> +    test "delete_product/1 deletes the product", %{product: product} do
Foi removido do redis e elastic?

2022-04-13 18:28 UTC, NoahCamargo commented on phoenix/app/products_manager/test/products_manager/contexts/manager_test.exs
> +      assert %Ecto.Changeset{} = Manager.change_product(product)
Essa função deveria ser privada, não? Já que a mesma só é chamada de dentro do próprio modelo

2022-04-13 18:28 UTC, NoahCamargo commented on phoenix/app/products_manager/test/products_manager/contexts/manager_test.exs
> +    :timer.sleep(2000)
Porque esse sleep?

2022-04-13 18:28 UTC, NoahCamargo commented on phoenix/app/products_manager/test/products_manager_web/controllers/product_controller_test.exs
No index, valide o response quando retornar um produto

2022-04-13 18:28 UTC, NoahCamargo commented on phoenix/app/products_manager/test/products_manager_web/controllers/product_controller_test.exs
>      test "renders errors when data is invalid", %{conn: conn} do
Verifique se o payload do erro veio como esperava, apenas olhar se não veio um map vazio abre margem para uma resposta fora de padrão vir sem que seja percebido no teste

2022-04-13 18:28 UTC, NoahCamargo commented on phoenix/app/products_manager/test/products_manager_web/controllers/product_controller_test.exs
>      test "renders errors when data is invalid", %{conn: conn, product: product} do
Verifique se o payload do erro veio como esperava, apenas olhar se não veio um map vazio abre margem para uma resposta fora de padrão vir sem que seja percebido no teste

2022-04-22 21:30 UTC, kristiansantos commented on phoenix/app/products_manager/test/products_manager/contexts/manager_test.exs
> +  describe "Update product" do
Testes implementado no teste da controller.

2022-04-22 21:30 UTC, kristiansantos commented on phoenix/app/products_manager/test/products_manager/contexts/manager_test.exs
> +  describe "Delete product" do
Testes implementado no teste da controller.

2022-04-22 21:30 UTC, kristiansantos commented on phoenix/app/products_manager/test/products_manager/contexts/manager_test.exs
> +  describe "List products" do
Ajustado.

2022-04-22 21:30 UTC, kristiansantos commented on phoenix/app/products_manager/test/products_manager/services/elasticsearch_test.exs
> +defmodule ProductsManager.ElasticSearchTest do
Alteração realizada.

2022-04-22 21:30 UTC, kristiansantos commented on phoenix/app/products_manager/test/products_manager/services/redis_test.exs
> +defmodule ProductsManager.RedisTest do
Alteração realizada.

2022-04-22 21:31 UTC, kristiansantos commented on phoenix/app/products_manager/lib/products_manager/services/elasticsearch.ex
>    def get_all(array_conditions, source) do
Alteração realizada.

2022-04-22 21:31 UTC, kristiansantos commented on phoenix/app/products_manager/test/products_manager/contexts/manager_test.exs
> +    test "list_products/0 returns all products", %{product: product} do
Implementação dos testes na base de dados realizados.

2022-04-22 21:32 UTC, kristiansantos commented on phoenix/app/products_manager/test/products_manager/contexts/manager_test.exs
> +    test "list_products/1 returns search products", %{product: product} do
Implementação dos testes na base de dados realizado.

2022-04-22 21:32 UTC, kristiansantos commented on phoenix/app/products_manager/test/products_manager/contexts/manager_test.exs
> +    test "get_product/1 returns the product with given id", %{product: product} do
Teste deletado como solicitado pelo @leoribeiro36.

2022-04-22 21:33 UTC, kristiansantos commented on phoenix/app/products_manager/test/products_manager/contexts/manager_test.exs
> +  describe "Create products" do
Validação realizada nos mocks.

2022-04-22 21:33 UTC, kristiansantos commented on phoenix/app/products_manager/test/products_manager/contexts/manager_test.exs
> +      assert %Ecto.Changeset{} = Manager.change_product(product)
Ajuste realizado.

2022-04-22 21:34 UTC, kristiansantos commented on phoenix/app/products_manager/test/products_manager/contexts/manager_test.exs
> +    :timer.sleep(2000)
O teste estava executando muito rapido e elasticsearch não indexa o dado no mesmo tempo. por isso essa "gambiarra" mas já foi removido.

2022-04-22 22:32 UTC, kristiansantos commented on phoenix/app/products_manager/test/products_manager_web/controllers/product_controller_test.exs
>      test "renders errors when data is invalid", %{conn: conn} do
Ajuste realizado.

2022-04-22 22:33 UTC, kristiansantos commented on phoenix/app/products_manager/test/products_manager_web/controllers/product_controller_test.exs
>      test "renders errors when data is invalid", %{conn: conn, product: product} do
Ajuste realizado.

2022-04-22 22:47 UTC, kristiansantos commented on phoenix/app/products_manager/test/products_manager_web/controllers/product_controller_test.exs
Ajuste realizado.

2022-04-25 19:51 UTC, NoahCamargo requested changes

2022-04-25 19:51 UTC, NoahCamargo commented on phoenix/app/products_manager/lib/products_manager/services/elasticsearch.ex
> +
Entre a primeira linha de comando dentro do modulo e a assinatura do modulo não tem espaço

2022-04-25 19:51 UTC, NoahCamargo commented on phoenix/app/products_manager/lib/products_manager/services/redis.ex
> +      {:ok, binary} -> {:ok, decode(binary)}
Se der erro no decode a resposta vai ficar meio estranha. `{:ok, {:error, SOMETHING}}`

2022-04-25 19:51 UTC, NoahCamargo commented on phoenix/app/products_manager/test/products_manager/contexts/manager_test.exs
> +  describe "list_products/0" do
Aqui na nomenclatura esta errado, pois o Manager.list_products(%{}) esta recebendo um parâmetro

2022-04-25 19:51 UTC, NoahCamargo commented on phoenix/app/products_manager/test/products_manager/contexts/manager_test.exs
> +    test "With error returns the product with the given id in database", %{product: product} do
No caso ele retornou erro, não o produto no banco

2022-04-25 19:51 UTC, NoahCamargo commented on phoenix/app/products_manager/test/products_manager/contexts/manager_test.exs
> +      assert {:error, :not_found} = Manager.get_product("722a744bdf29eb0151000000")
Esse testes esta como o anterior, mas o titulo esta se encaixando aqui

2022-04-25 19:51 UTC, NoahCamargo commented on phoenix/app/products_manager/test/products_manager/contexts/manager_test.exs
> +      assert %Ecto.Changeset{valid?: false} = response
Verifique se os erros retornados são os esperados

2022-04-25 19:51 UTC, NoahCamargo commented on phoenix/app/products_manager/test/products_manager/contexts/manager_test.exs
> +      assert %Ecto.Changeset{valid?: false} = response
Como aqui voce mockou o redis e o elasticsearch e passou valores inválidos, segundo o código nem chegou a chamar o mock e mesmo assim o teste passou, o que indica que mesmo que você mock mas não chame a função, o teste passara, então, nesse caso, no teste de sucesso tem que fazer de uma forma a validar se o mock foi chamado

2022-04-25 19:51 UTC, NoahCamargo commented on phoenix/app/products_manager/test/products_manager/contexts/manager_test.exs
> +      redis_get_by_mock(product.id)
Se falhou a verificação seria se esse cara não foi chamado

2022-04-25 19:51 UTC, NoahCamargo commented on phoenix/app/products_manager/test/products_manager/contexts/manager_test.exs
> +      assert product = get_product
Esse match apenas esta jogando o valor de get_product para product, não falhara nunca

2022-04-25 19:51 UTC, NoahCamargo commented on phoenix/app/products_manager/test/products_manager_web/controllers/product_controller_test.exs
> +    test "lists all products without data", %{conn: conn} do
Acho que ficaria melhor um titulo como "returns empty data"

2022-04-25 19:51 UTC, NoahCamargo commented on phoenix/app/products_manager/test/products_manager/models/product_test.exs
> +defmodule ProductsManager.ProductTest do
Faltou um teste do modulo de elasticsearch e redis

2022-04-26 00:10 UTC, kristiansantos commented on phoenix/app/products_manager/lib/products_manager/services/elasticsearch.ex
> +
Ajustado.

2022-04-26 00:17 UTC, kristiansantos commented on phoenix/app/products_manager/test/products_manager/contexts/manager_test.exs
> +    test "With error returns the product with the given id in database", %{product: product} do
Ajustado.

2022-04-26 00:18 UTC, kristiansantos commented on phoenix/app/products_manager/test/products_manager/contexts/manager_test.exs
> +      assert {:error, :not_found} = Manager.get_product("722a744bdf29eb0151000000")
Ajustado

2022-04-26 12:29 UTC, kristiansantos commented on phoenix/app/products_manager/test/products_manager/contexts/manager_test.exs
> +  describe "list_products/0" do
O serviço index sempre recebe o params na request, se ele for branco o valor correpondente será %{},  dessa forma no arquivo contexts/manager.ex existem 2 metodos cuja aridade é igual mas o primeiro tem uma condição, caso receba dessa forma vai retorna todos os dados sem aplicar filtro.

2022-04-26 12:33 UTC, kristiansantos commented on phoenix/app/products_manager/test/products_manager_web/controllers/product_controller_test.exs
> +    test "lists all products without data", %{conn: conn} do
Ajustado.

2022-04-26 12:38 UTC, kristiansantos commented on phoenix/app/products_manager/test/products_manager/contexts/manager_test.exs
> +      assert %Ecto.Changeset{valid?: false} = response
Ajustado o mock não era necessario nesse caso de teste.

2022-04-26 13:06 UTC, kristiansantos commented on phoenix/app/products_manager/test/products_manager/contexts/manager_test.exs
> +      assert product = get_product
Ajustado.

2022-05-03 13:08 UTC, kristiansantos commented on phoenix/app/products_manager/test/products_manager/models/product_test.exs
> +defmodule ProductsManager.ProductTest do
Implementado, somente não foi implementado nos casos onde o metodo usava só a lib.

2022-05-03 15:00 UTC, NoahCamargo requested changes

2022-05-03 15:00 UTC, NoahCamargo commented on phoenix/app/products_manager/test/products_manager/services/elasticsearch_test.exs
> +  @source "product"
seria melhor "products"

2022-05-03 15:00 UTC, NoahCamargo commented on phoenix/app/products_manager/test/products_manager/services/elasticsearch_test.exs
> +    setup [:data_fixture]
Como esta tudo mockado não precisa desse cara

2022-05-03 15:00 UTC, NoahCamargo commented on phoenix/app/products_manager/lib/products_manager/services/elasticsearch.ex
> +    do: @tirexs_http.put("#{path()}/#{source}/#{data.id}", data)
Em casos assim, a gente costuma validar se a URL chegou certo no mock. Nesse caso se chegou "http://172.0.0.1:product/IDIDIDIDIDIDIDID"

2022-05-03 15:00 UTC, NoahCamargo commented on phoenix/app/products_manager/test/products_manager/services/redis_test.exs
> +    setup [:data_fixture]
Como esta tudo mockado, não precisa desse cara

2022-05-03 15:00 UTC, NoahCamargo commented on phoenix/app/products_manager/test/products_manager/services/redis_test.exs
> +    setup [:data_fixture]
Como esta tudo mockado, não precisa desse cara

2022-05-03 15:00 UTC, NoahCamargo commented on phoenix/app/products_manager/test/products_manager/models/product_test.exs
> +defmodule ProductsManager.ProductTest do
O nome do teste, por padrão segue o nome do modulo com o sufixo Test, nesse caso ProductsManager.Models.ProductTest

2022-05-03 15:00 UTC, NoahCamargo commented on phoenix/app/products_manager/test/products_manager_web/controllers/product_controller_test.exs
>      end
Geralmente a gente faz assim:

```
    test "renders product when data is valid", %{conn: conn} do
      cached_and_indexed_data_mock(@create_attrs)

      response =
        conn
        |> post(Routes.product_path(conn, :create), product: @create_attrs)
        |> json_response(201)

      assert %{"id" => id} = response["data"]
      assert Repo.get(Product, id) != nil
    end
```

2022-05-03 17:08 UTC, kristiansantos commented on phoenix/app/products_manager/test/products_manager/services/elasticsearch_test.exs
> +    setup [:data_fixture]
Ajustado.

2022-05-03 17:09 UTC, kristiansantos commented on phoenix/app/products_manager/test/products_manager/services/redis_test.exs
> +    setup [:data_fixture]
Ajustado.

2022-05-03 17:09 UTC, kristiansantos commented on phoenix/app/products_manager/test/products_manager/services/redis_test.exs
> +    setup [:data_fixture]
Ajustado.

2022-05-03 18:13 UTC, kristiansantos commented on phoenix/app/products_manager/test/products_manager_web/controllers/product_controller_test.exs
>      end
Ajustado.

2022-05-04 13:33 UTC, kristiansantos commented on phoenix/app/products_manager/lib/products_manager/services/elasticsearch.ex
> +    do: @tirexs_http.put("#{path()}/#{source}/#{data.id}", data)
Ajustado.

2022-05-05 17:59 UTC, ArthurFreitas approved these changes

2022-05-05 18:16 UTC, merged